### ISSUE TITLE
Enable debugging

### ISSUE THREAD

**Issue by elkwood** [breach/node-thrust#3]
We need a way to debug in the browser. Whether it's by exposing the remote debugging port or by embedding the chrome debugger in the window doesn't matter. I just need a way in inspect the page being rendered.

**Comment by spolu** [comment]
Both are available. An API will be added for each of them for the windows' main documents.
<webview> debugging will go through use of the debugging url.

**Comment by spolu** [comment]
Fixed by 2aa446854bafcf79f1d377068c453dec80ac5b74
